runtime: php72

# env_variables:

# MYSQL_USER: root

# MYSQL_PASSWORD: ""

# MYSQL_DSN: mysql:dbname=soccer_api;unix_socket=/cloudsql/soccer-api-227216:us-central1:apiubor

# beta_settings:

# cloud_sql_instances: "soccer-api-227216:us-central1:apiubor"
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    MYSQL_USER: USER
    MYSQL_PASSWORD: PASSWORD
    MYSQL_DSN: mysql:dbname=soccer_api;unix_socket=/cloudsql/soccer-api-227216:us-central1:apiubor
    
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "soccer-api-227216:us-central1:apiubor"